import { Controller, Get } from '@nestjs/common';
import { environment } from '../../environments/environment';

@Controller('msx')
export class MsxController {
  @Get('start.json')
  getStart() {
    return {
      name: `MSX Player Template (${environment.production ? 'PROD' : 'DEV'})`,
      version: '1.0.0',
      parameter: `content:${environment.frontendUrl}/msx`,
      note: "this file generated by NestJS",
      welcome: 'none'
    };
  }
}
